Add OpenTelemetry

diff --git a/.github/workflows/deploy-dev.yaml b/.github/workflows/deploy-dev.yaml
--- a/.github/workflows/deploy-dev.yaml
+++ b/.github/workflows/deploy-dev.yaml
@@ -21,6 +21,7 @@ jobs:
         run: |
           echo "$PRIVATE_KEY" > key.pem
           chmod 400 key.pem
+
           ssh -o StrictHostKeyChecking=no -i key.pem $EC2_USER@$EC2_HOST << 'EOF'
             cd /home/ubuntu
 
@@ -30,8 +31,14 @@ jobs:
             fi
 
             cd yolo-dev
-            git pull origin dev
+
+            # Clean up old Git issues
+            rm -f .git/index.lock
+            git gc --prune=now
+            git fsck --full || true
+
             git checkout dev
+            git pull origin dev
 
             # Run the deployment script
             bash deploy-dev.sh
